Models/Plato.cs
using System;
namespace Proyecto1.Models
{
    public class Plato
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Imagen { get; set; }
        public decimal Precio { get; set; }
        public string Categoria { get; set; }
    }


}

Models/Reserva.cs
namespace Proyecto1.Models
{
    public class Reserva
    {
        public int NumeroReserva { get; set; }
        public DateTime FechaHoraReserva { get; set; }
        public string NombreCliente { get; set; }
        public int NumeroPersonas { get; set; }
    }


}

Models/Venta.cs
namespace Proyecto1.Models
{
    public class Venta
    {
        public int NumeroOrden { get; set; }
        public DateTime FechaHoraVenta { get; set; }
        public string NombrePlatoVendido { get; set; }
        public decimal CantidadVendida { get; set; }
    }


}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;


namespace Proyecto1.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }
  
}

Controllers/PlatosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Proyecto1.Models;
using Proyecto1.Services;

namespace Proyecto1.Views
{
    public class PlatosController : Controller
    {
        private readonly ICRUDService<Plato> _platos;
        public PlatosController(ICRUDService<Plato> platos)
        {
            _platos = platos;
        }
        public IActionResult Index()
        {
            return View(_platos.Get());
        }
        [HttpGet]
        public Plato GetById([FromQuery] int id)
        {
            return _platos.GetById("Id",id);
        }
        [HttpPost]
        public string Crear([FromBody]Plato plato)
        {
            string result = "";

            if (plato == null || string.IsNullOrWhiteSpace(plato.Categoria) ||
                string.IsNullOrWhiteSpace(plato.Descripcion)||
                string.IsNullOrWhiteSpace(plato.Nombre)||
                plato.Precio<1|| string.IsNullOrWhiteSpace(plato.Imagen))
            {
                return "Existen datos erróneos o incompletos";
            }
            
            plato.Id = _platos.CountAll() + 1;//asignar un id
            return _platos.Add(plato);
        }
        [HttpPut]
        public string Update([FromBody] Plato plato)
        {
            string result = "";

            if (plato == null || string.IsNullOrWhiteSpace(plato.Categoria) ||
                string.IsNullOrWhiteSpace(plato.Descripcion) ||
                string.IsNullOrWhiteSpace(plato.Nombre) ||
                plato.Precio < 1 || string.IsNullOrWhiteSpace(plato.Imagen))
            {
                return "Existen datos erróneos o incompletos";
            }
            return _platos.Update(plato,"Id",plato.Id);
        }
        [HttpDelete]
        public string Delete([FromBody] int id)
        {
            return _platos.Delete("Id", id);
        }

    }
}

Controllers/ReservasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Proyecto1.Models;
using Proyecto1.Services;

namespace Proyecto1.Views
{
    public class ReservasController : Controller
    {
        private readonly ICRUDService<Reserva> _reservas;
        public ReservasController(ICRUDService<Reserva> reservas)
        {
            _reservas = reservas;
        }
        // GET: Reservas
        public ActionResult Index()
        {
            return View(_reservas.Get());
        }


        [HttpGet]
        public Reserva GetById([FromQuery] int id)
        {
            return _reservas.GetById("NumeroReserva", id);
        }
        [HttpPost]
        public string Crear([FromBody] Reserva reserva)
        {
            string result = "";

            if (reserva == null || string.IsNullOrWhiteSpace(reserva.NombreCliente) ||
                reserva.NumeroPersonas < 1 )
            {
                return "Existen datos erróneos o incompletos";
            }

            reserva.NumeroReserva = _reservas.CountAll() + 1;//asignar un id
            return _reservas.Add(reserva);
        }
        [HttpPut]
        public string Update([FromBody] Reserva reserva)
        {
            string result = "";

            if (reserva == null || string.IsNullOrWhiteSpace(reserva.NombreCliente) ||
                 reserva.NumeroPersonas < 1)
            {
                return "Existen datos erróneos o incompletos";
            }
            return _reservas.Update(reserva, "NumeroReserva", reserva.NumeroReserva);
        }
        [HttpDelete]
        public string Delete([FromBody] int id)
        {
            return _reservas.Delete("NumeroReserva", id);
        }


    }
}

Controllers/VentasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Proyecto1.Models;
using Proyecto1.Services;

namespace Proyecto1.Views
{
    public class VentasController : Controller
    {
        private readonly ICRUDService<Venta> _ventas;
        public VentasController(ICRUDService<Venta> ventas)
        {
            _ventas = ventas;
        }
        public ActionResult Index()
        {
            return View(_ventas.Get());
        }


        [HttpGet]
        public Venta GetById([FromQuery] int id)
        {
            return _ventas.GetById("NumeroOrden", id);
        }
        [HttpPost]
        public string Crear([FromBody] Venta venta)
        {
            string result = "";

            if (venta == null || string.IsNullOrWhiteSpace(venta.NombrePlatoVendido) ||
                venta.CantidadVendida < 1)
            {
                return "Existen datos erróneos o incompletos";
            }

            venta.NumeroOrden = _ventas.CountAll() + 1;//asignar un id
            return _ventas.Add(venta);
        }
        [HttpPut]
        public string Update([FromBody] Venta venta)
        {
            string result = "";

            if (venta == null || string.IsNullOrWhiteSpace(venta.NombrePlatoVendido) ||
                venta.CantidadVendida < 1)
            {
                return "Existen datos erróneos o incompletos";
            }
            return _ventas.Update(venta, "NumeroOrden", venta.NumeroOrden);
        }
        [HttpDelete]
        public string Delete([FromBody] int id)
        {
            return _ventas.Delete("NumeroOrden", id);
        }
    }
}

Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<style>
    

    .header {
        background-color: #f1f1f1;
        text-align: center;
        padding: 20px;
        height: 100%;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }

        .header h1 {
            margin: 0;
        }

    .button-container {
        display: flex;
        flex-direction: row;
        justify-content: center;
        align-items: center;
        margin: 20px;
    }

    .button {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        margin: 20px;
        padding: 20px;
        color: white;
        justify-content: center;
        background-color: #2c3e50;
        text-align: center;
        text-decoration: none;
        cursor: pointer;
        border-radius: 5px;
        width: 300px;
        height: 150px;
    }

        .button:hover {
            background-color: darkcyan;
        }

        .button i {
            font-size: 5vh;
            margin-bottom: 10px;
            color: white;
            width: 80%;
        }

        .button span {
            width: 100%;
            font-size: 4vh;
        }
</style>

<div class="header">
    <h1>Proyecto 1- Richard Víquez</h1>
    <div class="button-container">
        <a href="@Url.Action("Index", "Platos")" class="button">

            <span>Platos</span>
            <i class="fas fa-utensils"></i>
        </a>
        <a href="@Url.Action("Index", "Ventas")" class="button">

            <span>Ventas</span>
            <i class="fas fa-chart-line"></i>
        </a>
        <a href="@Url.Action("Index", "Reservas")" class="button">

            <span>Reservas</span>
            <i class="fas fa-calendar-alt"></i>
        </a>
    </div>
</div>

Views/Platos/Index.cshtml
<style>

    .remove {
        color: white;
        background-color: #ff4757;
    }

    .tablescroll {
        overflow-y: scroll;
    }

    #btncrear {
        margin-top: 1vh;
        background: linear-gradient(176deg, rgba(3,104,221,1) 0%, rgba(21,31,133,1) 40%, rgba(29,102,187,1) 100%);
        color: white;
        padding: 1vh;
        min-width: 25%;
        text-align: center;
    }
    #btnagregar {
        margin-top: 1vh;
        background: #341f97;
        color: white;
        padding: 1vh;
        min-width: 25%;
        text-align: center;
    }
    #btneditar {
        margin-top: 1vh;
        background: #222f3e;
        color: white;
        padding: 1vh;
        min-width: 25%;
        text-align: center;
    }
    .blocks{
        display:grid;
        width:100%;
        height:100%;
        grid-template-columns:repeat(auto-fill,minmax(12rem,1fr));
        grid-column-gap:1px;
        grid-auto-rows:12rem;
    }
    .block {
        display: grid;
        max-height: 12rem;
        min-width: 99%;
        height: 100%;
        width: 99%;
        grid-template-rows: 20% 60% 20%;
        text-align: center;
        background-color:white;
        box-shadow: 2px 2px 8px 4px #d3d3d3d1;
        border-radius: 15px;
    }
    .block img{
        max-width:100%;
        max-height:100%;
        width:100%;
        height:100%;
    }
    .block a{
        width:100%;
    }
    h1,h2{
        text-align:center;
    }

    #btnvolver {
        margin-top: 1vh;
        background: #341f97;
        color: white;
        padding: 1vh;
        min-width: 25%;
        text-align: center;
    }
   
</style>


<div class="container-fluid" style="margin-top:2vh;margin-bottom:1vh;">
    <div class="row">
        <button id="btnvolver" class="btn button" >
            <i class="fas fa-arrow-left"></i> Volver atrás
        </button>
        <div class="col-md-6 form">
            <h1>Mantenimiento de Platos</h1>
            <h2>Crear  Plato</h2>
            <div>
                <div class="form-group">
                    <label for="nombre">Nombre:</label>
                    <input type="text" value="" class="form-control" id="nombre" name="nombre" required>
                </div>
                <div class="form-group">
                    <label for="descripcion">Descripción:</label>
                    <textarea class="form-control" id="descripcion" name="descripcion" required>
                    </textarea>
                </div>
                <div class="form-group">
                    <label for="precio">Precio:</label>
                    <input type="number" value="0" class="form-control" id="precio" name="precio" required>
                </div>
                <div class="form-group">
                    <label for="link">Link de la imágen:</label>
                    <input type="text" value="" class="form-control" id="link" name="link" required>
                </div>
                <div class="form-group">
                    <label for="categoria">Categoría:</label>
                    <select class="form-control" id="categoria" name="categoria" required>
                        <option value="local">Local</option>
                        <option value="extranjero">Extranjero</option>
                    </select>
                </div>
                <button id="btnagregar" class="btn button">Crear Nuevo</button>
                <button id="btneditar" disabled class="btn button">Modificar</button>
                <button id="btncrear" disabled class="btn button">Guardar</button>
            </div>
        </div>

        <div class="col-md-6">
            <h2>Lista de Platos</h2>

            <div class="blocks">
                @foreach (var plato in Model)
                {
                    <div class="block" data-id="@plato.Id">
                        <div style="overflow: hidden; text-overflow: ellipsis; width: 100%; max-width: 100%; white-space: nowrap;">@plato.Nombre</div>
                        <img src="@plato.Imagen" style="max-width: 100%;max-height:100%"/>
                        <div class="removebtns" data-id="@plato.Id">
                            <a href="@Url.Action("Eliminar",
                                    new { id = plato.Id })"
                               class="btn btn-sm remove">Eliminar</a>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<script defer>
    var selected = 0;
    var nombre = document.querySelector('#nombre');
    var descripcion = document.querySelector('#descripcion');
    var precio = document.querySelector('#precio');
    var categoria = document.querySelector('#categoria');
    var link = document.querySelector('#link');
    var btncrear = document.querySelector('#btncrear');
    var btnagregar = document.querySelector('#btnagregar');
    var btneditar = document.querySelector('#btneditar');
    var blocks = document.querySelectorAll('.block');
    var removes = document.querySelectorAll('.removebtns');

    var btnvolver = document.querySelector('#btnvolver');

    btnvolver.addEventListener('click', (e) => {
        e.preventDefault();
        window.history.back();
    });

    removes.forEach((rem) => {
        rem.addEventListener('click', async(e) => {
            e.preventDefault();
            e.stopPropagation();
            let id = rem.dataset.id;
            selected = id;
            await eliminarPlato(id);
        });
    });
    blocks.forEach( (block)=> {
        block.addEventListener('click', async(e) => {
            e.preventDefault();
            e.stopPropagation();
            let id = block.dataset.id;
            selected = id;
            btneditar.disabled = false;
            btncrear.disabled = true;
            await obtenerPlato(id);
        });
    });

    btnagregar.addEventListener('click', async (e) => {
        e.preventDefault();
        reset();
    });

    btncrear.addEventListener('click', async (e) => {
        e.preventDefault();
        await crearPlato();
    });

    btneditar.addEventListener('click', async (e) => {
        e.preventDefault();
        if (selected == 0) {
            alert('Debe seleccionar un plato primero!');
            return false;
        }
        await modificarPlato(selected);
    });

    async function obtenerPlato(id) {
        try {

            // Enviar la solicitud al servidor 
            let response = await fetch('/Platos/GetById?id='+id, {
                method: 'GET',
                headers: {
                    'Content-Type': 'application/json'
                }
            });

            // Verificar el estado de la respuesta
            if (response.ok) {
                let result = await response.json();
                nombre.value = result.nombre;
                descripcion.value = result.descripcion;
                precio.value = result.precio;
                categoria.value = result.categoria;
                link.value = result.imagen;
            } else {
                alert('Error en la solicitud');
                selected = 0;
                reset();
            }
        } catch (error) {
            reset();
            selected = 0;
            alert(error);
        }
    }

    function reset()
    {
        nombre.value = '';
        descripcion.value = '';
        precio.value = '';
        categoria.value = '';
        link.value = '';
        selected = 0;
        btneditar.disabled = true;
        btncrear.disabled = false;
    }
    async function crearPlato() {
        try {
          
            let data = {
                nombre: nombre.value,
                descripcion: descripcion.value,
                precio: precio.value,
                categoria: categoria.value,
                imagen: link.value
            };

            // Enviar la solicitud al servidor 
            let response = await fetch('/Platos/Crear', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify(data)
            });

            // Verificar el estado de la respuesta
            if (response.ok) {
                let result = await response.text();
                if (result == null ||
                    result == undefined
                    || result == typeof (undefined)
                    || result == typeof(null)||
                    !result.includes('correctamente')) {

                    alert(result);
                    return false;
                }
                alert(result);
                location.href = "/Platos";
            } else {
                alert('Error en la solicitud');
            }
            
        } catch (error) {
            reset();
            alert(error);
        }
    }

    async function modificarPlato(id) {
        try {

            let data = {
                id: id,
                nombre: nombre.value,
                descripcion: descripcion.value,
                precio: precio.value,
                categoria: categoria.value,
                imagen: link.value
            };

            // Enviar la solicitud al servidor 
            let response = await fetch('/Platos/Update', {
                method: 'PUT',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify(data)
            });

            // Verificar el estado de la respuesta
            if (response.ok) {
                let result = await response.text();
                alert(result);
            } else {
                alert('Error en la solicitud');
            }
            location.href = "/Platos";
        } catch (error) {
            reset();
            alert(error);
        }
    }

    async function eliminarPlato(id) {
        try {

            let data = id;

            // Enviar la solicitud al servidor 
            let response = await fetch('/Platos/Delete', {
                method: 'DELETE',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify(data)
            });

            // Verificar el estado de la respuesta
            if (response.ok) {
                let result = await response.text();
                alert(result);
            } else {
                alert('Error en la solicitud');
            }
            location.href = "/Platos";
        } catch (error) {
            reset();
            alert(error);
        }
    }
</script>

Views/Reservas/Index.cshtml
<style>

    .remove {
        color: white;
        background-color: #ff4757;
    }

    .tablescroll {
        overflow-y: scroll;
    }

    #btncrear {
        margin-top: 1vh;
        background: linear-gradient(176deg, rgba(3,104,221,1) 0%, rgba(21,31,133,1) 40%, rgba(29,102,187,1) 100%);
        color: white;
        padding: 1vh;
        min-width: 25%;
        text-align: center;
    }

    #btnagregar {
        margin-top: 1vh;
        background: #341f97;
        color: white;
        padding: 1vh;
        min-width: 25%;
        text-align: center;
    }

    #btneditar {
        margin-top: 1vh;
        background: #222f3e;
        color: white;
        padding: 1vh;
        min-width: 25%;
        text-align: center;
    }

    .blocks {
        display: grid;
        width: 100%;
        height: 100%;
        grid-template-columns: repeat(auto-fill,minmax(12rem,1fr));
        grid-column-gap: 1px;
        grid-auto-rows: 12rem;
    }

    .block {
        display: grid;
        max-height: 12rem;
        min-width: 99%;
        height: 100%;
        width: 99%;
        grid-template-rows: 20% 60% 20%;
        text-align: center;
        background-color: white;
        box-shadow: 2px 2px 8px 4px #d3d3d3d1;
        border-radius: 15px;
    }

        .block img {
            max-width: 100%;
            max-height: 100%;
            width: 100%;
            height: 100%;
        }

        .block a {
            width: 100%;
        }

    h1, h2 {
        text-align: center;
    }

    #btnvolver {
        margin-top: 1vh;
        background: #341f97;
        color: white;
        padding: 1vh;
        min-width: 25%;
        text-align: center;
    }
</style>


<div class="container-fluid" style="margin-top:2vh;margin-bottom:1vh;">
    <div class="row">
        <button id="btnvolver" class="btn button">
            <i class="fas fa-arrow-left"></i> Volver atrás
        </button>
        <div class="col-md-6 form">
            <h1>Mantenimiento de Reservaciones</h1>
            <h2>Crear Reservación</h2>
            <div>
                <div class="form-group">
                    <label for="nombre">Nombre del Cliente:</label>
                    <input type="text" value="" class="form-control" id="nombreCliente" name="nombre" required>
                </div>
                <div class="form-group">
                    <label for="fecha">Fecha de la reservación:</label>
                    <input type="datetime-local"
                           min="@DateTime.Now.ToString("yyyy-MM-ddTHH:mm")"
                           value="@DateTime.Now.ToString("yyyy-MM-ddTHH:mm")"
                           id="fechaHoraReserva" />

                </div>
                <div class="form-group">
                    <label for="personas">Número de Personas:</label>
                    <input type="number" value="0" class="form-control" id="numeroPersonas" name="personas" required>
                </div>
                <button id="btnagregar" class="btn button">Crear Nuevo</button>
                <button id="btneditar" disabled class="btn button">Modificar</button>
                <button id="btncrear" disabled class="btn button">Guardar</button>
            </div>
        </div>

        <div class="col-md-6">
            <h2>Lista de Reservaciones</h2>

            <div class="blocks">
                @foreach (var reserva in Model)
                {
                    <div class="block" data-id="@reserva.NumeroReserva">
                        <div><h2 style="overflow: hidden; text-overflow: ellipsis; width: 100%; max-width: 100%; white-space: nowrap; ">@reserva.NombreCliente</h2></div>
                        <div><h6 style="overflow: hidden; text-overflow: ellipsis; width: 100%; max-width: 100%; white-space: nowrap; ">@reserva.FechaHoraReserva</h6></div>
                        <div><h1 style="overflow: hidden; text-overflow: ellipsis; width: 100%; max-width: 100%; white-space: nowrap; ">@reserva.NumeroPersonas</h1></div>
                        <div class="removebtns" data-id="@reserva.NumeroReserva">
                            <a href="@Url.Action("Eliminar",
                                    new { id = reserva.NumeroReserva })"
                               class="btn btn-sm remove">Eliminar</a>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<script defer>var selected = 0;
    var nombreCliente = document.querySelector('#nombreCliente');
    var fechaHoraReserva = document.querySelector('#fechaHoraReserva');
    var numeroPersonas = document.querySelector('#numeroPersonas');
    var btncrear = document.querySelector('#btncrear');
    var btnagregar = document.querySelector('#btnagregar');
    var btneditar = document.querySelector('#btneditar');
    var blocks = document.querySelectorAll('.block');
    var removes = document.querySelectorAll('.removebtns');

    var btnvolver = document.querySelector('#btnvolver');

    btnvolver.addEventListener('click', (e) => {
        e.preventDefault();
        window.history.back();
    });

    removes.forEach((rem) => {
        rem.addEventListener('click', async(e) => {
            e.preventDefault();
            e.stopPropagation();
            let id = rem.dataset.id;
            selected = id;
            await eliminarReserva(id);
        });
    });
    blocks.forEach( (block)=> {
        block.addEventListener('click', async(e) => {
            e.preventDefault();
            e.stopPropagation();
            let id = block.dataset.id;
            selected = id;
            btneditar.disabled = false;
            btncrear.disabled = true;
            await obtenerReserva(id);
        });
    });

    btnagregar.addEventListener('click', async (e) => {
        e.preventDefault();
        reset();
    });

    btncrear.addEventListener('click', async (e) => {
        e.preventDefault();
        await crearReservacion();
    });

    btneditar.addEventListener('click', async (e) => {
        e.preventDefault();
        if (selected == 0) {
            alert('Debe seleccionar una reservación primero!');
            return false;
        }
        await modificarReserva(selected);
    });

    async function obtenerReserva(id) {
        try {

            // Enviar la solicitud al servidor
            let response = await fetch('/Reservas/GetById?id='+id, {
                method: 'GET',
                headers: {
                    'Content-Type': 'application/json'
                }
            });

            // Verificar el estado de la respuesta
            if (response.ok) {
                let result = await response.json();
                nombreCliente.value = result.nombreCliente;
                fechaHoraReserva.value = result.fechaHoraReserva;
                numeroPersonas.value = result.numeroPersonas;

            } else {
                alert('Error en la solicitud');
                selected = 0;
                reset();
            }
        } catch (error) {
            reset();
            selected = 0;
            alert(error);
        }
    }

    function reset()
    {
        let fechaHora = new Date();


        let year = fechaHora.getFullYear();
        let month = String(fechaHora.getMonth() + 1).padStart(2, '0');
        let day = String(fechaHora.getDate()).padStart(2, '0');
        let hours = String(fechaHora.getHours()).padStart(2, '0');
        let minutes = String(fechaHora.getMinutes()).padStart(2, '0');

        let fechaHoraFormateada = year + '-' + month + '-' + day + 'T' + hours + ':' + minutes;

        fechaHoraReserva.value = fechaHoraFormateada;
        nombreCliente.value = '';
        numeroPersonas.value = '';
        selected = 0;
        btneditar.disabled = true;
        btncrear.disabled = false;
    }
    async function crearReservacion() {
        try {

            let data = {
                nombreCliente: nombreCliente.value,
                fechaHoraReserva: fechaHoraReserva.value,
                numeroPersonas: numeroPersonas.value
            };

            // Enviar la solicitud al servidor
            let response = await fetch('/Reservas/Crear', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify(data)
            });

            // Verificar el estado de la respuesta
            if (response.ok) {
                let result = await response.text();
                if (result == null ||
                    result == undefined
                    || result == typeof (undefined)
                    || result == typeof(null)||
                    !result.includes('correctamente')) {

                    alert(result);
                    return false;
                }
                alert(result);
                location.href = "/Reservas";
            } else {
                alert('Error en la solicitud');
            }

        } catch (error) {
            reset();
            alert(error);
        }
    }

    async function modificarReserva(id) {
        try {

            let data = {
                numeroReserva:id,
                nombreCliente: nombreCliente.value,
                fechaHoraReserva: fechaHoraReserva.value,
                numeroPersonas: numeroPersonas.value
            };

            // Enviar la solicitud al servidor
            let response = await fetch('/Reservas/Update', {
                method: 'PUT',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify(data)
            });

            // Verificar el estado de la respuesta
            if (response.ok) {
                let result = await response.text();
                alert(result);
            } else {
                alert('Error en la solicitud');
            }
            location.href = "/Reservas";
        } catch (error) {
            reset();
            alert(error);
        }
    }

    async function eliminarReserva(id) {
        try {

            let data = id;

            // Enviar la solicitud al servidor
            let response = await fetch('/Reservas/Delete', {
                method: 'DELETE',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify(data)
            });

            // Verificar el estado de la respuesta
            if (response.ok) {
                let result = await response.text();
                alert(result);
            } else {
                alert('Error en la solicitud');
            }
            location.href = "/Reservas";
        } catch (error) {
            reset();
            alert(error);
        }
    }</script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Proyecto1</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css" integrity="sha512-NhSC1YmyruXifcj/KFRWoC561YpHpc5Jtzgvbuzx5VozKpWvQ+4nXhPdFgmx8xqexRcpAglTj9sIBWINXa8x5w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/global.css" />
    <link rel="stylesheet" href="~/Proyecto1.styles.css" asp-append-version="true" />
</head>
<body>
   
   @RenderBody()
     
  
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>